//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2sp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("m2sp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2sp.Resources.MorrisRomanBlack.ttf.
        /// </summary>
        internal static string AppFontName {
            get {
                return ResourceManager.GetString("AppFontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2sp.Resources.background.png.
        /// </summary>
        internal static string BackgroundImg {
            get {
                return ResourceManager.GetString("BackgroundImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2sp.Resources.correct.png.
        /// </summary>
        internal static string CorrectImg {
            get {
                return ResourceManager.GetString("CorrectImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2sp.Resources.Sound.correct.wav.
        /// </summary>
        internal static string CorrectSound {
            get {
                return ResourceManager.GetString("CorrectSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2sp.Resources.element_death.png.
        /// </summary>
        internal static string DeathImg {
            get {
                return ResourceManager.GetString("DeathImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2sp.Resources.element_earth.png.
        /// </summary>
        internal static string EarthImg {
            get {
                return ResourceManager.GetString("EarthImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2sp.Resources.element_fire.png.
        /// </summary>
        internal static string FireImg {
            get {
                return ResourceManager.GetString("FireImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2sp.Resources.element_frost.png.
        /// </summary>
        internal static string FrostImg {
            get {
                return ResourceManager.GetString("FrostImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2sp.Resources.element_ice.png.
        /// </summary>
        internal static string IceImg {
            get {
                return ResourceManager.GetString("IceImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2sp.Resources.element_life.png.
        /// </summary>
        internal static string LifeImg {
            get {
                return ResourceManager.GetString("LifeImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2sp.Resources.element_lightning.png.
        /// </summary>
        internal static string LightningImg {
            get {
                return ResourceManager.GetString("LightningImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2sp.Resources.element_poison.png.
        /// </summary>
        internal static string PoisonImg {
            get {
                return ResourceManager.GetString("PoisonImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2sp.Resources.element_shield.png.
        /// </summary>
        internal static string ShieldImg {
            get {
                return ResourceManager.GetString("ShieldImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2sp.Resources.Magicks.spell1.jpg.
        /// </summary>
        internal static string SpellImg1 {
            get {
                return ResourceManager.GetString("SpellImg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2sp.Resources.Magicks.spell10.jpg.
        /// </summary>
        internal static string SpellImg10 {
            get {
                return ResourceManager.GetString("SpellImg10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2sp.Resources.Magicks.spell11.jpg.
        /// </summary>
        internal static string SpellImg11 {
            get {
                return ResourceManager.GetString("SpellImg11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2sp.Resources.Magicks.spell12.jpg.
        /// </summary>
        internal static string SpellImg12 {
            get {
                return ResourceManager.GetString("SpellImg12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2sp.Resources.Magicks.spell13.jpg.
        /// </summary>
        internal static string SpellImg13 {
            get {
                return ResourceManager.GetString("SpellImg13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2sp.Resources.Magicks.spell14.jpg.
        /// </summary>
        internal static string SpellImg14 {
            get {
                return ResourceManager.GetString("SpellImg14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2sp.Resources.Magicks.spell15.jpg.
        /// </summary>
        internal static string SpellImg15 {
            get {
                return ResourceManager.GetString("SpellImg15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2sp.Resources.Magicks.spell16.jpg.
        /// </summary>
        internal static string SpellImg16 {
            get {
                return ResourceManager.GetString("SpellImg16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2sp.Resources.Magicks.spell17.jpg.
        /// </summary>
        internal static string SpellImg17 {
            get {
                return ResourceManager.GetString("SpellImg17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2sp.Resources.Magicks.spell18.jpg.
        /// </summary>
        internal static string SpellImg18 {
            get {
                return ResourceManager.GetString("SpellImg18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2sp.Resources.Magicks.spell19.jpg.
        /// </summary>
        internal static string SpellImg19 {
            get {
                return ResourceManager.GetString("SpellImg19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2sp.Resources.Magicks.spell2.jpg.
        /// </summary>
        internal static string SpellImg2 {
            get {
                return ResourceManager.GetString("SpellImg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2sp.Resources.Magicks.spell3.jpg.
        /// </summary>
        internal static string SpellImg3 {
            get {
                return ResourceManager.GetString("SpellImg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2sp.Resources.Magicks.spell4.jpg.
        /// </summary>
        internal static string SpellImg4 {
            get {
                return ResourceManager.GetString("SpellImg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2sp.Resources.Magicks.spell5.jpg.
        /// </summary>
        internal static string SpellImg5 {
            get {
                return ResourceManager.GetString("SpellImg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2sp.Resources.Magicks.spell6.jpg.
        /// </summary>
        internal static string SpellImg6 {
            get {
                return ResourceManager.GetString("SpellImg6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2sp.Resources.Magicks.spell7.jpg.
        /// </summary>
        internal static string SpellImg7 {
            get {
                return ResourceManager.GetString("SpellImg7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2sp.Resources.Magicks.spell8.jpg.
        /// </summary>
        internal static string SpellImg8 {
            get {
                return ResourceManager.GetString("SpellImg8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2sp.Resources.Magicks.spell9.jpg.
        /// </summary>
        internal static string SpellImg9 {
            get {
                return ResourceManager.GetString("SpellImg9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2sp.Resources.element_steam.png.
        /// </summary>
        internal static string SteamImg {
            get {
                return ResourceManager.GetString("SteamImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2sp.Resources.element_water.png.
        /// </summary>
        internal static string WaterImg {
            get {
                return ResourceManager.GetString("WaterImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2sp.Resources.wrong.png.
        /// </summary>
        internal static string WrongImg {
            get {
                return ResourceManager.GetString("WrongImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2sp.Resources.Sound.wrong.wav.
        /// </summary>
        internal static string WrongSound {
            get {
                return ResourceManager.GetString("WrongSound", resourceCulture);
            }
        }
    }
}
